name: simple_calculator
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  adaptive_navigation: ^0.0.10
  animated_splash_screen: ^1.3.0
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  go_router: ^14.2.1
  html: ^0.15.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  page_transition: ^2.1.0
  path_to_regexp: ^0.4.0
  quiver: ^3.2.1
  fluttertoast: ^8.2.6
  dropdown_textfield: ^1.2.0
  url_launcher: ^6.3.0
  url_strategy: ^0.2.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  pretty_dio_logger: ^1.4.0
  intl: ^0.19.0
  flutter_widget_from_html: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
