// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlgrCgMZtCH7rJ26XOFCwCP2LKAxwQA_w',
    appId: '1:455780667365:web:bbf29e5a25af56bf36690c',
    messagingSenderId: '455780667365',
    projectId: 'simple-calculator-a962f',
    authDomain: 'simple-calculator-a962f.firebaseapp.com',
    storageBucket: 'simple-calculator-a962f.appspot.com',
    measurementId: 'G-JKKF80ZT2X',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASWsMQhn7UAem_RoBHqJTuVPskwsEL_2U',
    appId: '1:455780667365:ios:45a67981027c5fb036690c',
    messagingSenderId: '455780667365',
    projectId: 'simple-calculator-a962f',
    storageBucket: 'simple-calculator-a962f.appspot.com',
    iosBundleId: 'com.example.simpleCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlgrCgMZtCH7rJ26XOFCwCP2LKAxwQA_w',
    appId: '1:455780667365:web:7ffba9ac035d3d6036690c',
    messagingSenderId: '455780667365',
    projectId: 'simple-calculator-a962f',
    authDomain: 'simple-calculator-a962f.firebaseapp.com',
    storageBucket: 'simple-calculator-a962f.appspot.com',
    measurementId: 'G-LZ37J4PKQZ',
  );

}